### ISSUE TITLE
Hardcoded Email Address

### ISSUE THREAD

**Issue by Bourne-ID** [aws-samples/amazon-api-gateway-url-shortener#14]
https://github.com/aws-samples/amazon-api-gateway-url-shortener/blob/153e6627006b486fddb3b67cc062b419b27c141a/templates/app/linkId/put-request.json#L18

Looks like a PR put in a hard-coded email address opposed to `$context.authorizer.claims.email`

**Comment by singledigit** [comment]
Thanks ... merged
