### ISSUE TITLE
Stack building is failed because of "CloudWatch Logs role ARN must be set in account settings to enable logging"

### ISSUE THREAD

**Issue by tarunjangra** [aws-samples/amazon-api-gateway-url-shortener#20]
**Dev Environment**

SAM CLI, version 1.0.0
aws-cli/2.0.33 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev37

When I start the deployment using command `sam deploy -g`, It is getting failed in between with the following message of failure.

> CloudWatch Logs role ARN must be set in account settings to enable logging   (Service: AmazonApiGateway; Status Code:400; Error Code: BadRequestException; Request ID: 58541396-e90b-418c-a8c5-8ae495604e75)

I am able to figure out this problem by adding following policy in the template.yml 
<pre>
  CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  Account:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt 
        - CloudWatchRole
        - Arn
</pre>
Now it is getting deployed as expected.

After successful deployment I can see the landing Magic home page but when i click on Signup/Login I am getting following error.

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BFD2F9DAC0C76C7E</RequestId>
<HostId>u1cmt0WOo96vP9naC7HW5aRd7N7aBzSQse9e0llXByYRQX8B5OIOxtR/JmEjZmw2iQJhvjf33NU=</HostId>
</Error>`
I am not sure what am I missing here.

**Comment by leeboy1984** [comment]
Hi,

Same here, adding to this, also when you try to access CloudFront distribution it gives you an error of "missing authentication token"

**Comment by guswls1846** [comment]
HI 
So, I changed the VUE_APP_API_ROOT of amplify environment variable to api gateway url format with a little trick.

https://d3l2kugsjmxxx.cloudfront.net 
Instead of 
https://shortener-733166xxx.auth.ap-northeast-2.amazoncognito.com

**Comment by leeboy1984** [comment]
Still not working:

VUE_APP_NAME=shortener
VUE_APP_CLIENT_ID=<correct_key>
VUE_APP_API_ROOT=https://d1gsiy461fiXXX.cloudfront.net
VUE_APP_AUTH_DOMAIN=https://bsit-shortener-ZZZZZZZZZz.auth.eu-west-1.amazoncognito.com

Any idea?

**Comment by guswls1846** [comment]
> Any idea?
It's my .env

VUE_APP_NAME=shortener
VUE_APP_API_ROOT=https://g7849hm****.execute-api.ap-northeast-2.amazonaws.com/Prod
VUE_APP_AUTH_DOMAIN=https://shortener-73316615xxxx.auth.ap-northeast-2.amazoncognito.com
VUE_APP_CLIENT_ID=4vo8i2q00hubv75********

**Comment by DavideFranchioni** [comment]
@tarunjangra Can you share your full template?

**Comment by singledigit** [comment]
Added the cloudwatch update.

**Comment by singledigit** [comment]
Reopen if access issues still occur
